### ISSUE TITLE
SFA R package

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#10]
Related to #9 : it might be straightforward to natively support SFA the similar way we've done it for `extreme_decov`, ie, make an `sfar` package out of it, unless licensing is an issue.

**Comment by stephens999** [comment]
it could be interesting. However, I hope we might make flashr our default approach here instead of SAF. Only downside is that flashr is currently potentially slower? (haven't checked carefully
but seems inevitable). flashr has the advantage of being
more accurate, also already in R, and I am hopeful we can speed it up.

**Comment by gaow** [comment]
Related to #17 : 

At the very list the procedure to run SFA is [demonstrated here](http://stephenslab.github.io/gtex-eqtls/analysis/20171002_MASH_V8.html#SFA) with output saved as RDS file, and using the results in mashr is [demonstrated here](http://stephenslab.github.io/gtex-eqtls/analysis/20171002_MASH_V8.html#Create-and-refine-multi-rank-covariance-matrices).

**Comment by gaow** [comment]
We will use `flashr` to replace SFA.
