### ISSUE TITLE
log10BF goes to infinity

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#35]
Test data-set: 
[mashr_issue_35.tar.gz](https://github.com/stephenslab/mashr/files/1986095/mashr_issue_35.tar.gz)

Test script:

```r
attach(readRDS('mashr_issue_35.rds'))
mash_data = mashr::mash_set_data(B,S,V=V)
mout = mashr::mash(mash_data, g = fitted_g, fixg = TRUE)       
# - Computing 1001 x 155 likelihood matrix.
# - Likelihood calculations took 0.13 seconds.
# - Computing posterior matrices.
# - Computation allocated took 0.01 seconds.
l10bf = mashr::get_log10bf(mout)
max(l10bf)
# [1] Inf
min(l10bf)   
# [1] -0.6563015
min(mout$null_loglik)
# -Inf
```

It looks like some log-likelihood under the null is `-inf`. Is this some standard numerical errors that has a standard way to get around?

**Comment by stephens999** [comment]
i looked into it. This happens because we have designed only to preserve numerical precision when comparing between models that are competitive with the "best" model. If the null is not competitive we lose precision. Here Inf is not a bad indication of the BF, it means that exp(log10bf) is Inf to numerical precision. But we could indeed do better with a different design if it mattered.
The key is that
calc_relative_lik_matrix
returns a likelihood matrix (which we do need!). If it also returned the log-likelihood matrix
we could keep numerical precision at the cost of the additional memory.

So, the question is whether it ever really matters in practice? Do we really need to distinguish between BFs that are >10^300?

**Comment by stephens999** [comment]
@gaow i'll deal with this

**Comment by gaow** [comment]
Thank you @stephens999 for having identified the problem and to handle it! It would be nice to deal with it if the cost is not that big.

**Comment by stephens999** [comment]
please try it out!

**Comment by gaow** [comment]
Thank you @stephens999 it works on that example, and certainly helped distinguishing large BF's:

```
1012.15461146687
1011.42046097444
1011.42046097444
1011.42046097444
1011.42046097444
1011.42046097444
1011.42046097444
1011.42046097444
953.381956068478
869.491883825122
818.280042860037
818.280042860037
749.635908266495
749.635908266495
749.635908266495
645.999004011303
638.560666132322
542.760379878343
498.208920039631
498.208920039631
472.167241393688
432.48604633603
368.725957896725
...
```
