### ISSUE TITLE
Get Travis CI & Appveyor working again

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/mashr#54]
This will most likely involve revising the configuration to install GSL.

**Comment by gaow** [comment]
@pcarbo do you know if installing `RcppGSL` will automatically install usable GSL libraries to link to? Would be nice to find it out with those CI's.

**Comment by pcarbo** [comment]
It does not install GSL.

**Comment by pcarbo** [comment]
Note it is confusing because `RcppGSL` from CRAN can be installed without GSL; I suspect this is because it is statically linked to the GSL libraries by the CRAN people.

**Comment by pcarbo** [comment]
Travis CI is working now. @gaow says he will attempt to get Appveyor working. We wish him luck.

**Comment by gaow** [comment]
No luck for Appveyor for now. I might make more progress given a Windows machine to test it and apply [some hacks](https://stackoverflow.com/questions/23640088/setting-up-rcpp-gsl-for-windows). It is otherwise hard to work it out. But it does not bother me to claim that Windows users are responsible to figure out gsl installation on their own in order to use mashr.

**Comment by pcarbo** [comment]
@gaow I'm closing this, but feel free to re-open it if you prefer.
